common:
    resource: "@CommonBundle/Controller/"
    type:     annotation
    prefix:   /

coordinate:
    resource: "@CoordinateBundle/Controller/"
    type:     annotation
    prefix:   /

person:
    resource: "@PersonBundle/Controller/"
    type:     annotation
    prefix:   /

site:
    resource: "@SiteBundle/Controller/"
    type:     annotation
    prefix:   /
